services:

    # PHP Service
    app:
        image: "php8.2-node18-python3.11"
        container_name: "app_microscopia"
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "5173:5173" # Mapea el puerto del host al contenedor para Vite
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /mnt/storage/web-files/microscopia-archivos/:/var/archivo_microscopia
            - /mnt/storage/backups/:/var/respaldo
            #- /home/ivanelterrible/.ssh/:/home/www/.ssh/
        networks:
            - app-network

    # Nnginx Service
    webserver:
        image: "nginx:alpine3.18-slim"
        container_name: "webserver_microscopia"
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /mnt/storage/web-files/microscopia-archivos/:/var/archivo_microscopia
            - /mnt/storage/backups/:/var/respaldo
        networks:
            - app-network
        depends_on:
            - app

    # MariaDB Service
    db:
        image: "mariadb:10.8.2"
        container_name: "db_microscopia"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root-laravel
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
            - /mnt/storage/backups/:/var/respaldo
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local